name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Create packman
    runs-on: ubuntu-latest

    steps:
      - name: Create packman and load
        uses: felipefms/pacman-contribution-graph@v1
        with:
          github_user_name: furylemons
          output_filepath: github-pacman.svg
